###Datasurce and DB configs
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/nextTravelPVTTravelPackageService?createDatabaseIfNotExist=true
#spring.datasource.username=root
#spring.datasource.password=1234
##spring.datasource.hikari.maximum-pool-size=5
#
###Data JPA and Hibernate configs
#spring.jpa.generate-ddl=true
#spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.format_sql=true
#
###Other configs
#server.port=9082
#server.servlet.context-path=/nextTravelPVTLtdTravelPackage


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

##Datasurce and DB configs
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nextTravelPVTTravelPackageService?createDatabaseIfNotExist=true
    username: root
    password: 1234

  jpa:
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  application:
    name: PACKAGE-SERVICE

server:
  port: 9082
  servlet:
    context-path: /nextTravelPVTLtdTravelPackage