eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

server:
  port: 9083
  servlet:
    context-path: /nextTravelPVTLtdGuideService

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/nextTravelGuideServer
  application:
    name: GUIDE-SERVICE
